{% set version = "2.2.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spotifyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spotifyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spotifyr/spotifyr_{{ version }}.tar.gz
  sha256: 3212158e404dbd82162da74f8e01dbab5671abb9ff366b7ba07e78babf273893

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-httr
    - r-janitor
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-rlang
    - r-rvest
    - r-stringr
    - r-tibble
    - r-xml2
  run:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-httr
    - r-janitor
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-rlang
    - r-rvest
    - r-stringr
    - r-tibble
    - r-xml2

test:
  commands:
    - $R -e "library('spotifyr')"           # [not win]
    - "\"%R%\" -e \"library('spotifyr')\""  # [win]

about:
  home: http://github.com/charlie86/spotifyr
  license: MIT
  summary: An R wrapper for pulling data from the 'Spotify' Web API  <http://developer.spotify.com/web-api> in bulk. It allows you to enter  an artist's name and retrieve their entire discography in seconds, along  with audio features and lyrics from Genius Lyrics <https://www.genius.com>.  You can also pull song and playlist
    information for a given 'Spotify' user.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
