appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xicPD3HdGq8fj96Ss7ipmwZvXeNqaMso2FFIFUUF1TDpeTN13LX67s1Ra6ZeOuZku+kC56qBWjfizo1TzqnnJgyjRYOhmrmK9ojRZ1hRQ5pXyGLFzJPm8t1swPBhjt62GVJRxuGq4/acNGt/afKDLWfs7P9cwCjehKpz7c6y7xrVGNoF6Qa7HbNqQykbmkBlD77PNGQ4kfjONdbviOE+d+bUsn3DO26gQZVmUJVqIsU3Pn+XoEzR13CtNSyqJWneqnkEDbxEUsm6/v2dhYapw2bj9Bx68O/1F4QilF3sTmggq4r800PvpQZncaObSm3/8cpfvlbjTZ0x/5zzRcO7GuvB73GvuNf6VQMzPLNKd6IiboMwuQfBjjsQ7vlaLjcsXzDUh9f+0qert1b6mCwJAVnyx1TbH2EykB1aP0OOLynuAWujl1FkKqoAocVnWqcxk1b1mRRJh3SYYOBGRuKNN12KJ86ghepC1jeBmC3WL0kpoD46WtVdynBLBLLMHCQEG/fDslbXG+GA8yjZ8lm9nF+UeodgHW/9mPFkspUOSLDNabqfuyGc+u7+0PN+GzdSajO2nhKotZWurOnzgmI1OVauwVDg49EGYpZucDM161mzMZk/JhoKn4HbwRGfGaHuErS5u2lgwqy4OswKs5kraxWRsCjYU25nGzsNbM34/aU=}
